name = "cert-gen"
compatibility_date = "2024-12-17"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[vars]
CERT_KEY = "my-super-secret-key"

[[d1_databases]]
binding = "DB"
database_name = "gptc-certificates-db"
database_id = "2bb0e27f-13df-4fae-8ab3-12b972756728"
migrations_dir = "drizzle"

